### ISSUE TITLE
Not informative enough

### ISSUE THREAD

**Issue by l-Fingon-l** [MrSmoKkkk98/ukraineflag#1]
# Hi! 
Your website is so great. But could you please add some text to it?  

What I want is a description of the greatness of Ukraine in the centre of flags!  
***Like this:***  

![image](https://user-images.githubusercontent.com/70348701/171031266-841a0c0d-981b-4777-995a-9ed814929d5c.png)

**Comment by MrSmoKkkk98** [comment]
Ok, I will look at that.

**Comment by MrSmoKkkk98** [comment]
8872ae82c693ffcc6fd500c1c289ed630963cc59

**Comment by l-Fingon-l** [comment]
> I [fixed](https://github.com/MrSmoKkkk98/ukraineflag/commit/8872ae82c693ffcc6fd500c1c289ed630963cc59) the problem. [8872ae8](https://github.com/MrSmoKkkk98/ukraineflag/commit/8872ae82c693ffcc6fd500c1c289ed630963cc59)

I'm really sorry but this is light years away from what I've asked!   

![image](https://user-images.githubusercontent.com/70348701/171033638-bbe49b97-2fc6-46ee-9fd4-9802498c602e.png)

**Comment by MrSmoKkkk98** [comment]
Now I really [fixed] (https://github.com/MrSmoKkkk98/ukraineflag/commit/af67978e196df5fac60341fcfc3ef1c6ff22a952) the problem.

**Comment by l-Fingon-l** [comment]
Then you can close the issue! 
![image](https://user-images.githubusercontent.com/70348701/171278169-999ed8f6-6642-4924-9684-af5d8eda3c16.png)
